name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Publish
      run: |
        dotnet pack ${{ github.workspace }}/DisplaySettings/DisplaySettings.csproj -c Release
        dotnet publish ${{ github.workspace }}/DisplaySettings.Cli/DisplaySettings.Cli.csproj -c Release -f netcoreapp3.1 -r win-x64 -p:PublishSingleFile=true --no-self-contained
       
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: DisplaySettings
        path: |
          ${{ github.workspace }}/DisplaySettings/bin/Release/*.nupkg
          ${{ github.workspace }}/DisplaySettings.Cli/bin/Release/netcoreapp3.1/win-x64/publish/*.exe
        
    - name: Automatic release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Latest build"
        files: |
          ${{ github.workspace }}/DisplaySettings/bin/Release/*.nupkg
          ${{ github.workspace }}/DisplaySettings.Cli/bin/Release/netcoreapp3.1/win-x64/publish/*.exe
